/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { Login200, LoginRequest, MeResponse } from "../models";

/**
 * @summary Log in using email and password
 */
export const login = <TData = AxiosResponse<Login200>>(
  loginRequest: LoginRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/login`, loginRequest, options);
};
/**
 * @summary Get currently logged-in user.
 */
export const me = <TData = AxiosResponse<MeResponse>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/me`, options);
};
export type LoginResult = AxiosResponse<Login200>;
export type MeResult = AxiosResponse<MeResponse>;
