/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { IndexUsersResponse, ShowUserResponse } from "../models";

/**
 * @summary Index users.
 */
export const indexUsers = <TData = AxiosResponse<IndexUsersResponse>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/users`, options);
};
/**
 * @summary Show user by id.
 */
export const showUser = <TData = AxiosResponse<ShowUserResponse>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/users/${id}`, options);
};
export type IndexUsersResult = AxiosResponse<IndexUsersResponse>;
export type ShowUserResult = AxiosResponse<ShowUserResponse>;
