/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */
import type { Tag } from "./tag";

/**
 * Index tags response object.
 */
export interface IndexTagsResponse {
  data: Tag[];
  message: string;
}
