/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */
import type { User } from "./user";

/**
 * Index users response object.
 */
export interface IndexUsersResponse {
  data: User[];
  message: string;
}
