/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */
import type { Me } from "./me";

export type Login200Data = {
  token_type?: string;
  token?: string;
  user?: Me;
};
