/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */

/**
 * Request for logging in with email and password.
 */
export interface LoginRequest {
  email: string;
  password: string;
}
