/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */

/**
 * Me (User) resource object
 */
export interface Me {
  id: number;
  name: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  email_verified_at: string | null;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  updated_at: string | null;
}
