/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */
import type { Me } from "./me";

/**
 * Currently logged-in user response object.
 */
export interface MeResponse {
  data: Me;
  message: string;
}
