/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */

/**
 * Task visibility
 */
export type StoreTaskRequestVisibility =
  (typeof StoreTaskRequestVisibility)[keyof typeof StoreTaskRequestVisibility];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoreTaskRequestVisibility = {
  public: "public",
  private: "private",
} as const;
