/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */

/**
 * Request for creating a tag record.
 */
export interface StoreTagRequest {
  /** Tag name */
  name: string;
  /**
   * Tag description
   * @nullable
   */
  description?: string | null;
}
