/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */
import type { StoreTaskRequestStatus } from "./storeTaskRequestStatus";
import type { StoreTaskRequestVisibility } from "./storeTaskRequestVisibility";

/**
 * Request for creating a task record.
 */
export interface StoreTaskRequest {
  /** Task status */
  status: StoreTaskRequestStatus;
  /** Task visibility */
  visibility: StoreTaskRequestVisibility;
  /** Task title */
  title: string;
  /**
   * Task description
   * @nullable
   */
  description?: string | null;
  /** List of ALL the tag names that the task will have */
  tags?: string[];
}
