/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */

/**
 * Task status
 */
export type StoreTaskRequestStatus =
  (typeof StoreTaskRequestStatus)[keyof typeof StoreTaskRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoreTaskRequestStatus = {
  "to-do": "to-do",
  "in-progress": "in-progress",
  done: "done",
  canceled: "canceled",
} as const;
