/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */
import type { Task } from "./task";

/**
 * Store task response object.
 */
export interface StoreTaskResponse {
  data: Task;
  message: string;
}
