/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */

/**
 * Tag resource object
 */
export interface Tag {
  id: number;
  name: string;
  /** @nullable */
  description: string | null;
}
