/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */

/**
 * Task resource object
 */
export interface Task {
  id: number;
  user_id: number;
  status: string;
  title: string;
  /** @nullable */
  description: string | null;
  visibility: string;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  updated_at: string | null;
  tags?: string[];
}
