/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */

/**
 * Task visibility
 */
export type UpdateTaskRequestVisibility =
  (typeof UpdateTaskRequestVisibility)[keyof typeof UpdateTaskRequestVisibility];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateTaskRequestVisibility = {
  public: "public",
  private: "private",
} as const;
