/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */
import type { UpdateTaskRequestStatus } from "./updateTaskRequestStatus";
import type { UpdateTaskRequestVisibility } from "./updateTaskRequestVisibility";

/**
 * Request for updating a task record.
 */
export interface UpdateTaskRequest {
  /** Task status */
  status?: UpdateTaskRequestStatus;
  /** Task visibility */
  visibility?: UpdateTaskRequestVisibility;
  /** Task title */
  title?: string;
  /**
   * Task description
   * @nullable
   */
  description?: string | null;
  /** List of ALL the tag names that the task will have */
  tags?: string[];
}
