/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * tasker
 * OpenAPI spec version: 0.1
 */
import type { Tag } from "./tag";

/**
 * Update tag response object.
 */
export interface UpdateTagResponse {
  data: Tag;
  message: string;
}
